import {
  ActivityItem,
  Invoice,
  KnowledgeArticle,
  NotificationItem,
  Ticket,
} from "./types";

export const currentUser = {
  id: "u-1",
  name: "guest",
  email: "guest@supportflow.ai",
  role: "Support Lead",
  initials: "Gu",
};

export const tickets: Ticket[] = [
  {
    id: "SF-4012",
    subject: "API Integration failing on production environment",
    customer: "Mark Thompson",
    company: "CloudScale Inc.",
    priority: "Urgent",
    status: "Open",
    tag: "API",
    tags: ["production", "sync-api", "timeout"],
    createdAgo: "24m ago",
    assignee: "Alex R.",
    slaRemainingPct: 75,
    slaRemainingLabel: "45m",
    region: "US-East-1",
    mrr: "$4,250.00",
    healthScore: "Excellent",
    plan: "Enterprise Plan",
    since: "2021",
    messages: [
      {
        id: "m-1",
        author: "Jordan Smith",
        isAgent: false,
        timestamp: "10:14 AM",
        body: "Hello Team, we are experiencing persistent timeouts when calling the /v2/sync endpoint from our production servers. This started around 10:00 AM UTC. Could you please investigate if there are any service degradations?",
        attachment: { name: "error_logs_10-00.txt", meta: "2.4 MB · Text Document" },
      },
      {
        id: "m-2",
        author: "Alex Rivers",
        isAgent: true,
        isInternal: true,
        timestamp: "10:20 AM",
        body: "Internal Note: Backend logs show high latency in DB cluster 4.",
      },
      {
        id: "m-3",
        author: "Alex Rivers",
        isAgent: true,
        timestamp: "10:35 AM",
        body: "Hi Jordan, thank you for reaching out. I've flagged this with our DevOps team. We noticed a surge in latency in our European cluster. I'll update you as soon as I have a concrete ETA for the fix.",
      },
    ],
  },
  {
    id: "SF-3988",
    subject: "Subscription billing error on monthly renewal",
    customer: "Sarah Jenkins",
    company: "Lumina Tech",
    priority: "Medium",
    status: "Open",
    tag: "Billing",
    tags: ["billing", "renewal"],
    createdAgo: "2h ago",
    assignee: null,
    slaRemainingPct: 40,
    slaRemainingLabel: "3h 10m",
    region: "EU-West-2",
    mrr: "$1,120.00",
    healthScore: "Good",
    plan: "Growth Plan",
    since: "2023",
    messages: [
      {
        id: "m-1",
        author: "Sarah Jenkins",
        isAgent: false,
        timestamp: "09:02 AM",
        body: "Our card was charged twice for this month's renewal. Can someone take a look and refund the duplicate charge?",
      },
    ],
  },
  {
    id: "SF-3990",
    subject: "Bulk data export takes too long and crashes",
    customer: "Richard Lee",
    company: "Equinox Systems",
    priority: "High",
    status: "In Progress",
    tag: "Performance",
    tags: ["performance", "export"],
    createdAgo: "6h ago",
    assignee: "Marcus T.",
    slaRemainingPct: 55,
    slaRemainingLabel: "1h 40m",
    region: "AP-South-1",
    mrr: "$2,860.00",
    healthScore: "Good",
    plan: "Growth Plan",
    since: "2022",
    messages: [
      {
        id: "m-1",
        author: "Richard Lee",
        isAgent: false,
        timestamp: "Yesterday",
        body: "Exporting more than 20k rows always times out around the 90% mark. This has been happening consistently since the last update.",
      },
    ],
  },
  {
    id: "SF-3912",
    subject: "Request for password reset link timeout",
    customer: "John Doe",
    company: "Aether Labs",
    priority: "Low",
    status: "Resolved",
    tag: "Account",
    tags: ["auth"],
    createdAgo: "Resolved 5h ago",
    assignee: "Auto-Bot",
    slaRemainingPct: 0,
    slaRemainingLabel: "—",
    region: "US-West-1",
    mrr: "$430.00",
    healthScore: "Good",
    plan: "Starter Plan",
    since: "2024",
    messages: [
      {
        id: "m-1",
        author: "John Doe",
        isAgent: false,
        timestamp: "2 days ago",
        body: "The password reset link keeps expiring before I can click it.",
      },
      {
        id: "m-2",
        author: "Auto-Bot",
        isAgent: true,
        timestamp: "2 days ago",
        body: "We've extended the reset link validity window to 30 minutes and issued you a new link. Let us know if you still run into trouble!",
      },
    ],
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: "a-1",
    icon: "user-plus",
    iconBg: "bg-secondary-container/30",
    iconColor: "text-secondary",
    text: "**Sarah Jenkins** joined the support team as Junior Lead.",
    time: "2 mins ago",
  },
  {
    id: "a-2",
    icon: "triangle-exclamation",
    iconBg: "bg-primary-container/20",
    iconColor: "text-primary",
    text: "Critical escalation: **Ticket #SF-4012** for CloudScale Inc.",
    time: "45 mins ago",
  },
  {
    id: "a-3",
    icon: "circle-check",
    iconBg: "bg-green-100",
    iconColor: "text-green-600",
    text: "System Status: **All nodes reporting healthy.**",
    time: "2 hours ago",
  },
  {
    id: "a-4",
    icon: "rotate",
    iconBg: "bg-surface-container-high",
    iconColor: "text-on-surface-variant",
    text: "Knowledge base updated: **v4.2 API Docs**",
    time: "5 hours ago",
  },
  {
    id: "a-5",
    icon: "comment-dots",
    iconBg: "bg-secondary-container/30",
    iconColor: "text-secondary",
    text: "**Marcus T.** posted a new internal memo.",
    time: "Yesterday",
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "n-1",
    group: "Today",
    variant: "urgent",
    icon: "triangle-exclamation",
    title: "Urgent: Server Latency Spike",
    body: "System detected a 40% increase in API latency across US-East-1. Automated scaling initiated. Please monitor the traffic dashboard.",
    time: "10m ago",
    read: false,
  },
  {
    id: "n-2",
    group: "Today",
    variant: "comment",
    icon: "comment-dots",
    title: "New mention from Sarah J.",
    body: "\u201c@AlexRivers can you review the SLAs for Ticket #SF-4012? The client is requesting an expedited resolution.\u201d",
    time: "2h ago",
    read: false,
  },
  {
    id: "n-3",
    group: "Yesterday",
    variant: "update",
    icon: "arrows-rotate",
    title: "Weekly Performance Report",
    body: "Your team achieved a 94% CSAT score this week. First Response Time improved by 12% compared to last period.",
    time: "Yesterday",
    read: true,
  },
  {
    id: "n-4",
    group: "Yesterday",
    variant: "muted",
    icon: "circle-check",
    title: "Ticket #SF-3912 Closed",
    body: "Account verification for 'Aether Labs' has been successfully completed and the ticket marked as resolved.",
    time: "Yesterday",
    read: true,
  },
];

export const knowledgeArticles: KnowledgeArticle[] = [
  {
    id: "kb-1",
    category: "Integration",
    readTime: "6 min read",
    title: "Configuring Webhooks for Real-Time Sync",
    excerpt:
      "Learn how to set up and secure webhook endpoints to keep your external systems in sync with SupportFlow in real-time.",
  },
  {
    id: "kb-2",
    category: "Billing",
    readTime: "3 min read",
    title: "Updating Payment Methods",
    excerpt:
      "A step-by-step walkthrough for updating your card on file, switching plans, and understanding proration.",
  },
  {
    id: "kb-3",
    category: "Best Practice",
    readTime: "4 min read",
    title: "Mastering Bulk Operations",
    excerpt:
      "Maximize efficiency by performing actions on hundreds of tickets simultaneously using our advanced selection tools.",
  },
  {
    id: "kb-4",
    category: "Analytics",
    readTime: "12 min read",
    title: "Understanding CSAT Reports",
    excerpt:
      "Dive deep into customer satisfaction metrics and learn how to identify trends in your team's performance data.",
  },
];

export const invoices: Invoice[] = [
  { id: "SF-2024-009", status: "Paid", date: "Sep 24, 2024", amount: "$149.00" },
  { id: "SF-2024-008", status: "Paid", date: "Aug 24, 2024", amount: "$149.00" },
  { id: "SF-2024-007", status: "Paid", date: "Jul 24, 2024", amount: "$149.00" },
];

export const ticketVolumeSeries = {
  labels: [
    "Jun 1",
    "Jun 2",
    "Jun 3",
    "Jun 4",
    "Jun 5",
    "Jun 6",
    "Jun 7",
    "Jun 8",
    "Jun 9",
    "Jun 10",
    "Jun 11",
    "Jun 12",
    "Jun 13",
    "Jun 14",
  ],
  newTickets: [65, 59, 80, 81, 56, 55, 40, 70, 75, 82, 90, 85, 78, 95],
  resolved: [45, 50, 60, 70, 60, 58, 45, 65, 68, 70, 80, 75, 82, 88],
};

export const deployments = [
  {
    id: "d-1",
    initials: "MS",
    name: "Mark Stevenson",
    email: "ms@supportflow.ai",
    status: "Successful" as const,
    region: "US-East-1",
    date: "2 mins ago",
  },
  {
    id: "d-2",
    initials: "JL",
    name: "Jane Luvia",
    email: "jane.l@supportflow.ai",
    status: "In Progress" as const,
    region: "EU-West-2",
    date: "15 mins ago",
  },
  {
    id: "d-3",
    initials: "RK",
    name: "Rick Kane",
    email: "rkane@supportflow.ai",
    status: "Successful" as const,
    region: "AP-South-1",
    date: "1 hr ago",
  },
];

export const leaderboard = [
  { rank: "01", name: "Sarah Chen", score: 142, pct: 85 },
  { rank: "02", name: "Jamie Ortiz", score: 118, pct: 72 },
  { rank: "03", name: "Maya Angel", score: 94, pct: 65 },
];
